## **Project Klasifikasi Sentimen Analisis**

In [5]:
#!pip install textblob

   ---------------------------------------- 0.0/626.3 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/626.3 kB ? eta -:--:--
   ---------------------------------------- 626.3/626.3 kB 3.3 MB/s eta 0:00:00


### **Library yang digunakan**

In [1]:
#library yang digunakan, jika dirasa kurang penting dapat dihapus
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import string
import re
from nltk import word_tokenize
import nltk
nltk.download('punkt')
nltk.download('stopwords')
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from wordcloud import WordCloud, STOPWORDS
from sklearn.metrics import ConfusionMatrixDisplay
from textblob import TextBlob
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\RESTU\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\RESTU\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [2]:
data = pd.read_csv("data/mobil_listrik.csv")
print(data.shape)

(1517, 5)


In [3]:
# Hapus baris yang memiliki NaN di kolom 'COMMENT' atau 'SENTIMEN'
data_clean = data.dropna(subset=['text_cleaning', 'sentimen'])

In [4]:
# Pisahkan lagi data
X = data_clean['text_cleaning']
y = data_clean['sentimen']

In [5]:
print(f"Jumlah baris X setelah cleaning: {X.shape[0]}")
print(f"Jumlah baris y setelah cleaning: {y.shape[0]}")

Jumlah baris X setelah cleaning: 1515
Jumlah baris y setelah cleaning: 1515


In [6]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import pandas as pd
import numpy as np

# Download stopwords jika belum terunduh
nltk.download('stopwords')
nltk.download('punkt')  # Untuk tokenisasi

# Fungsi untuk preprocessing teks
def preprocessing(text):
    if not isinstance(text, str):
        text = ""  # Berikan nilai default untuk non-string
    text = text.lower()
    text = re.sub(r'\d+', '', text)  # Hapus angka
    text = re.sub(r'[^\w\s]', '', text)  # Hapus karakter khusus
    text = text.strip()
    tokens = nltk.word_tokenize(text)  # Tokenisasi
    stop_words = set(stopwords.words('indonesian'))  # Stopwords bahasa Indonesia
    filtered_tokens = [token for token in tokens if token not in stop_words]  # Hilangkan stopwords
    stemmer = PorterStemmer()
    stemmed_tokens = [stemmer.stem(token) for token in filtered_tokens]  # Stemming
    return ' '.join(stemmed_tokens)

# Contoh DataFrame dengan data teks dan label sentimen
data = {
    'text': ["Ini adalah contoh teks.", np.nan, "Teks lain untuk diproses!"],
    'SENTIMEN': [1, 0, 1]  # Contoh label sentimen
}
# df = pd.DataFrame(data)

# # Pisahkan X dan y
# X = df['text']
# y = df['SENTIMEN']

# Terapkan preprocessing
X = X.fillna("")  # Ganti NaN dengan string kosong
X = X.apply(preprocessing)

print("Teks setelah preprocessing:")
print(X)


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\RESTU\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\RESTU\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


Teks setelah preprocessing:
0       saran sih bikin harga ionic kayak brio insya a...
1       problem subsidi kualita diturunin harga dinaik...
2       kualita kembang kualita motor motor pabrikan j...
3             model jelek kwalita buruk harga mahal croot
4       syarat ngaco woy anak muda blom rumah blom jd ...
                              ...                        
1512                                   kabar negri negara
1513    anak sekolah bantu pasar klw klw jebak macet a...
1514                                   esemka bangga solo
1515    cerda orang hni dn pasar jln x blom da gimana ...
1516    niat beli ev murah dinaikin perintah rakyat ka...
Name: text_cleaning, Length: 1515, dtype: object


In [8]:
# Lakukan vectorization pada teks
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(X)

In [9]:
# Lakukan pembagian dataset menjadi data training dan data testing
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
# Lakukan training model KNN
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [11]:
# Lakukan prediksi pada data testing
y_pred = knn.predict(X_test)

In [12]:
# Lakukan prediksi pada data testing
y_pred = knn.predict(X_test)

In [14]:
# Lakukan evaluasi model
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
cm = confusion_matrix(y_test, y_pred)

print('Accuracy:', accuracy)
print('Precision:', precision)
print('Recall:', recall)
print('F1 Score:', f1)
print('Confusion Matrix:\n', cm)

Accuracy: 0.594059405940594
Precision: 0.6031578221760795
Recall: 0.594059405940594
F1 Score: 0.588617462958694
Confusion Matrix:
 [[111   7  60]
 [ 12   3  12]
 [ 30   2  66]]
